exporter:
  port: 9010
log:
  # type is [logfmt or json]
  type: logfmt
  path: ./powerstoreExporter.out.log
  level: info
storageList:
  - ip: 10.0.0.1
    user: username
    password: password
    apiVersion: v1
