{
 "title": "Powerstore Export Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Group",
    "query": {}
   },
   {
    "name": "Hosts",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Name",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "Powerstore Cluster Name" },
       "itemTag": { "filter": "Application: cluster" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Cluster Global Id",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "Powerstore Cluster Global Id" },
       "itemTag": { "filter": "Application: cluster" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Cluster Master Id",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 6, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "Powerstore Cluster Master Id" },
       "itemTag": { "filter": "Application: cluster" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Cluster Address",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 10, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "Powerstore Cluster Address" },
       "itemTag": { "filter": "Application: cluster" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Service Tag",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 14, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "Powerstore Appliance Tag" },
       "itemTag": { "filter": "Application: appliance" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Cluster State",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 17, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "Powerstore Cluster State" },
       "itemTag": { "filter": "Application: cluster" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Perf Avg Io Workload Cpu Utilization",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:138",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": {
        "filter": "Appliance [A1]:Avg IO Workload Cpu Utilization"
       },
       "itemTag": { "filter": "Application: perf" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Performance Iops",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:32",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/IOPS/" },
       "itemTag": { "filter": "Application: perf" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Perf Avg Latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 9, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:59",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/Avg Latency/" },
       "itemTag": { "filter": "Application: perf" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Perf Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:86",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/Bandwidth/" },
       "itemTag": { "filter": "Application: perf" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Capacity Physical Total",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:551",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "Powerstore Capacity",
          " "
         ],
         "text": "replaceAlias(Powerstore Capacity,  )"
        },
        {
         "$$hashKey": "object:552",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/Last Physical Total/" },
       "itemTag": { "filter": "Application: capacity" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Capacity Logical Provisioned",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:32",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "Powerstore Capacity",
          " "
         ],
         "text": "replaceAlias(Powerstore Capacity,  )"
        },
        {
         "$$hashKey": "object:33",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/Last Logical Provisioned/" },
       "itemTag": { "filter": "Application: capacity" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Capacity Physical Used",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:609",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "Powerstore Capacity",
          " "
         ],
         "text": "replaceAlias(Powerstore Capacity,  )"
        },
        {
         "$$hashKey": "object:610",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/Last Physical Used/" },
       "itemTag": { "filter": "Application: capacity" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Capacity Percent Physical Used",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:638",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "Powerstore Capacity",
          " "
         ],
         "text": "replaceAlias(Powerstore Capacity,  )"
        },
        {
         "$$hashKey": "object:639",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/Last Physical Percent Used/" },
       "itemTag": { "filter": "Application: capacity" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Capacity Logical Used",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:667",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "Powerstore Capacity",
          " "
         ],
         "text": "replaceAlias(Powerstore Capacity,  )"
        },
        {
         "$$hashKey": "object:668",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/Last Logical Used/" },
       "itemTag": { "filter": "Application: capacity" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Capacity Efficiency Ratio",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 15, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:696",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "Powerstore Capacity",
          " "
         ],
         "text": "replaceAlias(Powerstore Capacity,  )"
        },
        {
         "$$hashKey": "object:697",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/Last Efficiency Ratio/" },
       "itemTag": { "filter": "Application: capacity" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Capacity Thin Savings",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 18, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:725",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "Powerstore Capacity",
          " "
         ],
         "text": "replaceAlias(Powerstore Capacity,  )"
        },
        {
         "$$hashKey": "object:726",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/Last Thin Savings/" },
       "itemTag": { "filter": "Application: capacity" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Capacity Data Reduction",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 21, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:754",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "Powerstore Capacity",
          " "
         ],
         "text": "replaceAlias(Powerstore Capacity,  )"
        },
        {
         "$$hashKey": "object:755",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/Last Data Reduction/" },
       "itemTag": { "filter": "Application: capacity" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Drives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Drives",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "rawSql": "select tab_all.vis_name host_name,\r\n  trim(substring_index(substring_index(tab_all.key_,'[',-1),']',1)) as node,\r\n  sum(case trim(substring_index(substring_index(tab_all.key_,'powerstore.hardware.drives.',-1),'.[',1)) when 'size' then tab_all.value end) as 'Drives Size',\r\n  sum(case trim(substring_index(substring_index(tab_all.key_,'powerstore.hardware.drives.',-1),'.[',1)) when 'status' then tab_all.value end) as 'Drives Status'\r\nfrom\r\n  (select tab1.vis_name,\r\n    tab1.host_name,\r\n    tab1.itemid,\r\n    tab1.item_name,\r\n    tab1.value,\r\n    tab1.key_\r\n   from (SELECT h.hostid\r\n           ,h.name   vis_name\r\n           ,h.host   host_name\r\n           ,i.itemid\r\n           ,i.name   item_name\r\n           ,i.key_\r\n           ,hs.clock\r\n           ,hs.value\r\n         FROM items i,hosts h,history hs,hosts_groups hg,hstgrp hstg\r\n         where h.hostid = i.hostid and i.itemid = hs.itemid and h.hostid = hg.hostid and hg.groupid = hstg.groupid\r\n           and hstg.name in ($Group)\r\n           and i.key_ like 'powerstore.hardware.drives.%'\r\n           and hs.clock > UNIX_TIMESTAMP(DATE_SUB(NOW(), INTERVAL 60 minute))) tab1\r\n   where tab1.clock=\r\n    (select max(clock)\r\n     from (SELECT h.hostid\r\n             ,h.name   vis_name\r\n             ,h.host   host_name\r\n             ,i.itemid\r\n             ,i.name   item_name\r\n             ,i.key_\r\n             ,hs.clock\r\n             ,hs.value\r\n           FROM items i,hosts h,history hs,hosts_groups hg,hstgrp hstg\r\n           where h.hostid = i.hostid and i.itemid = hs.itemid and h.hostid = hg.hostid and hg.groupid = hstg.groupid\r\n             and hstg.name in ($Group)\r\n             and i.key_ like 'powerstore.hardware.drives.%'\r\n             and hs.clock > UNIX_TIMESTAMP(DATE_SUB(NOW(), INTERVAL 60 minute))) tab2\r\n   where tab2.itemid = tab1.itemid)\r\n   union\r\n   select tab1.vis_name,\r\n    tab1.host_name,\r\n    tab1.itemid,\r\n    tab1.item_name,\r\n    tab1.value,\r\n    tab1.key_\r\n   from (SELECT h.hostid\r\n           ,h.name   vis_name\r\n           ,h.host   host_name\r\n           ,i.itemid\r\n           ,i.name   item_name\r\n           ,i.key_\r\n           ,hs.clock\r\n           ,hs.value\r\n         FROM items i,hosts h,history hs,hosts_groups hg,hstgrp hstg\r\n         where h.hostid = i.hostid and i.itemid = hs.itemid and h.hostid = hg.hostid and hg.groupid = hstg.groupid\r\n           and hstg.name in ($Group)\r\n           and i.key_ like 'powerstore.hardware.drives.%'\r\n           and hs.clock > UNIX_TIMESTAMP(DATE_SUB(NOW(), INTERVAL 60 minute))) tab1\r\n   where tab1.clock=\r\n    (select max(clock)\r\n     from (SELECT h.hostid\r\n             ,h.name   vis_name\r\n             ,h.host   host_name\r\n             ,i.itemid\r\n             ,i.name   item_name\r\n             ,i.key_\r\n             ,hs.clock\r\n             ,hs.value\r\n           FROM items i,hosts h,history hs,hosts_groups hg,hstgrp hstg\r\n           where h.hostid = i.hostid and i.itemid = hs.itemid and h.hostid = hg.hostid and hg.groupid = hstg.groupid\r\n             and hstg.name in ($Group)\r\n             and i.key_ like 'powerstore.hardware.drives.%'\r\n             and hs.clock > UNIX_TIMESTAMP(DATE_SUB(NOW(), INTERVAL 60 minute))) tab2\r\nwhere tab2.itemid = tab1.itemid)) tab_all where tab_all.vis_name = '$Hosts' group by node\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Port",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "EthPort CurrentSpeed",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:119",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "Powerstore EthPort CurrentSpeed",
          " "
         ],
         "text": "replaceAlias(Powerstore EthPort CurrentSpeed,  )"
        },
        {
         "$$hashKey": "object:120",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/CurrentSpeed/" },
       "itemTag": { "filter": "Application: ethport" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "EthPortIs Link Up",
     "type": "stat",
     "gridPos": { "h": 4, "w": 18, "x": 6, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:148",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "Powerstore FcPort Is Link Up",
          " "
         ],
         "text": "replaceAlias(Powerstore FcPort Is Link Up,  )"
        },
        {
         "$$hashKey": "object:149",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/Is Link Up/" },
       "itemTag": { "filter": "Application: ethport" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "FCPort CurrentSpeed",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:90",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "Powerstore EthPort Is Link Up",
          " "
         ],
         "text": "replaceAlias(Powerstore EthPort Is Link Up,  )"
        },
        {
         "$$hashKey": "object:91",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/CurrentSpeed/" },
       "itemTag": { "filter": "Application: fcport" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "FCPort Is Link Up",
     "type": "stat",
     "gridPos": { "h": 4, "w": 18, "x": 6, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:61",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "Powerstore FcPort CurrentSpeed",
          " "
         ],
         "text": "replaceAlias(Powerstore FcPort CurrentSpeed,  )"
        },
        {
         "$$hashKey": "object:62",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/Is Link Up/" },
       "itemTag": { "filter": "Application: fcport" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Volume",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Volume",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "rawSql": "select tab_all.vis_name host_name,\r\n  trim(substring_index(substring_index(tab_all.key_,'[',-1),']',1)) as node,\r\n  sum(case trim(substring_index(substring_index(tab_all.key_,'powerstore.volume.',-1),'.[',1)) when 'size' then tab_all.value end) as 'Volume Size',\r\n  sum(case trim(substring_index(substring_index(tab_all.key_,'powerstore.volume.',-1),'.[',1)) when 'state' then tab_all.value end) as 'Volume State'\r\nfrom\r\n  (select tab1.vis_name,\r\n    tab1.host_name,\r\n    tab1.itemid,\r\n    tab1.item_name,\r\n    tab1.value,\r\n    tab1.key_\r\n   from (SELECT h.hostid\r\n           ,h.name   vis_name\r\n           ,h.host   host_name\r\n           ,i.itemid\r\n           ,i.name   item_name\r\n           ,i.key_\r\n           ,hs.clock\r\n           ,hs.value\r\n         FROM items i,hosts h,history hs,hosts_groups hg,hstgrp hstg\r\n         where h.hostid = i.hostid and i.itemid = hs.itemid and h.hostid = hg.hostid and hg.groupid = hstg.groupid\r\n           and hstg.name in ($Group)\r\n           and i.key_ like 'powerstore.volume.%'\r\n           and hs.clock > UNIX_TIMESTAMP(DATE_SUB(NOW(), INTERVAL 60 minute))) tab1\r\n   where tab1.clock=\r\n    (select max(clock)\r\n     from (SELECT h.hostid\r\n             ,h.name   vis_name\r\n             ,h.host   host_name\r\n             ,i.itemid\r\n             ,i.name   item_name\r\n             ,i.key_\r\n             ,hs.clock\r\n             ,hs.value\r\n           FROM items i,hosts h,history hs,hosts_groups hg,hstgrp hstg\r\n           where h.hostid = i.hostid and i.itemid = hs.itemid and h.hostid = hg.hostid and hg.groupid = hstg.groupid\r\n             and hstg.name in ($Group)\r\n             and i.key_ like 'powerstore.volume.%'\r\n             and hs.clock > UNIX_TIMESTAMP(DATE_SUB(NOW(), INTERVAL 60 minute))) tab2\r\n   where tab2.itemid = tab1.itemid)\r\n   union\r\n   select tab1.vis_name,\r\n    tab1.host_name,\r\n    tab1.itemid,\r\n    tab1.item_name,\r\n    tab1.value,\r\n    tab1.key_\r\n   from (SELECT h.hostid\r\n           ,h.name   vis_name\r\n           ,h.host   host_name\r\n           ,i.itemid\r\n           ,i.name   item_name\r\n           ,i.key_\r\n           ,hs.clock\r\n           ,hs.value\r\n         FROM items i,hosts h,history_uint hs,hosts_groups hg,hstgrp hstg\r\n         where h.hostid = i.hostid and i.itemid = hs.itemid and h.hostid = hg.hostid and hg.groupid = hstg.groupid\r\n           and hstg.name in ($Group)\r\n           and i.key_ like 'powerstore.volume.%'\r\n           and hs.clock > UNIX_TIMESTAMP(DATE_SUB(NOW(), INTERVAL 60 minute))) tab1\r\n   where tab1.clock=\r\n    (select max(clock)\r\n     from (SELECT h.hostid\r\n             ,h.name   vis_name\r\n             ,h.host   host_name\r\n             ,i.itemid\r\n             ,i.name   item_name\r\n             ,i.key_\r\n             ,hs.clock\r\n             ,hs.value\r\n           FROM items i,hosts h,history_uint hs,hosts_groups hg,hstgrp hstg\r\n           where h.hostid = i.hostid and i.itemid = hs.itemid and h.hostid = hg.hostid and hg.groupid = hstg.groupid\r\n             and hstg.name in ($Group)\r\n             and i.key_ like 'powerstore.volume.%'\r\n             and hs.clock > UNIX_TIMESTAMP(DATE_SUB(NOW(), INTERVAL 60 minute))) tab2\r\nwhere tab2.itemid = tab1.itemid)) tab_all where tab_all.vis_name = '$Hosts' group by node\r\n"
      }
     ]
    },
    {
     "title": "Volume Avg Latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:2637",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "Avg Latency Total",
          " "
         ],
         "text": "replaceAlias(Avg Latency Total,  )"
        },
        {
         "$$hashKey": "object:2638",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/Avg Latency Total/" },
       "itemTag": {
        "filter": "Application: performance volume"
       },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Volume Avg Write Latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "Avg Latency Write",
          " "
         ],
         "text": "replaceAlias(Avg Latency Write,  )",
         "$$hashKey": "object:61"
        },
        {
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )",
         "$$hashKey": "object:62"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/Avg Latency Write/" },
       "itemTag": { "filter": "Application: metric volume" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Volume Avg Read Latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "Avg Latency Read",
          " "
         ],
         "text": "replaceAlias(Avg Latency Read,  )",
         "$$hashKey": "object:32"
        },
        {
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )",
         "$$hashKey": "object:33"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/Avg Latency Read/" },
       "itemTag": { "filter": "Application: metric volume" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Volume Avg Total Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "Avg Bandwidth Total",
          " "
         ],
         "text": "replaceAlias(Avg Bandwidth Total,  )",
         "$$hashKey": "object:90"
        },
        {
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )",
         "$$hashKey": "object:91"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/Avg Bandwidth Total/" },
       "itemTag": { "filter": "Application: metric volume" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Volume Avg Write Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "Avg Bandwidth Write",
          " "
         ],
         "text": "replaceAlias(Avg Bandwidth Write,  )",
         "$$hashKey": "object:148"
        },
        {
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )",
         "$$hashKey": "object:149"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/Avg Bandwidth Write/" },
       "itemTag": { "filter": "Application: metric volume" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Volume Avg Read Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "Avg Bandwidth Read",
          " "
         ],
         "text": "replaceAlias(Avg Bandwidth Read,  )",
         "$$hashKey": "object:119"
        },
        {
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )",
         "$$hashKey": "object:120"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/Avg Bandwidth Read/" },
       "itemTag": {
        "filter": "Application: performance volume"
       },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Volume Avg Total Iops",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "IOPS Total",
          " "
         ],
         "text": "replaceAlias(IOPS Total,  )",
         "$$hashKey": "object:177"
        },
        {
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )",
         "$$hashKey": "object:178"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/IOPS Total/" },
       "itemTag": {
        "filter": "Application: performance volume"
       },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Volume Avg Write Iops",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "IOPS Write",
          " "
         ],
         "text": "replaceAlias(IOPS Write,  )",
         "$$hashKey": "object:235"
        },
        {
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )",
         "$$hashKey": "object:236"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/IOPS Write/" },
       "itemTag": { "filter": "Application: metric volume" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Volume Avg Read Iops",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "IOPS Read",
          " "
         ],
         "text": "replaceAlias(IOPS Read,  )",
         "$$hashKey": "object:206"
        },
        {
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )",
         "$$hashKey": "object:207"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/IOPS Read/" },
       "itemTag": { "filter": "Application: metric volume" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "VolumeGroup",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Logical Provisioned",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:462",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          ": Logical Provisioned",
          " "
         ],
         "text": "replaceAlias(: Logical Provisioned,  )"
        },
        {
         "$$hashKey": "object:463",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts: Volume Group",
          " "
         ],
         "text": "replaceAlias($Hosts: Volume Group,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/Logical Provisioned/" },
       "itemTag": { "filter": "Application: volumegroup" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Logical Used",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:848",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          ": Logical Used",
          " "
         ],
         "text": "replaceAlias(: Logical Used,  )"
        },
        {
         "$$hashKey": "object:849",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts: Volume Group",
          " "
         ],
         "text": "replaceAlias($Hosts: Volume Group,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/ Logical Used/" },
       "itemTag": { "filter": "Application: volumegroup" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Total Iops",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:550",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "IOPS Total",
          " "
         ],
         "text": "replaceAlias(IOPS Total,  )"
        },
        {
         "$$hashKey": "object:551",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/IOPS Total/" },
       "itemTag": {
        "filter": "Application: performance volumegroup"
       },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Write Iops",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:728",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "IOPS Write",
          " "
         ],
         "text": "replaceAlias(IOPS Write,  )"
        },
        {
         "$$hashKey": "object:729",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/IOPS Write/" },
       "itemTag": {
        "filter": "Application: performance volumegroup"
       },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Read Iops",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:491",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          ":Powerstore MetricVg Read Iops",
          " "
         ],
         "text": "replaceAlias(:Powerstore MetricVg Read Iops,  )"
        },
        {
         "$$hashKey": "object:492",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/IOPS Read/" },
       "itemTag": {
        "filter": "Application: performance volumegroup"
       },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Total Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:554",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          ":Powerstore MetricVg Total Bandwidth",
          " "
         ],
         "text": "replaceAlias(:Powerstore MetricVg Total Bandwidth,  )"
        },
        {
         "$$hashKey": "object:555",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/Bandwidth Total/" },
       "itemTag": {
        "filter": "Application: performance volumegroup"
       },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Write Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:670",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          ":Powerstore MetricVg Write Bandwidth",
          " "
         ],
         "text": "replaceAlias(:Powerstore MetricVg Write Bandwidth,  )"
        },
        {
         "$$hashKey": "object:671",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/Bandwidth Write/" },
       "itemTag": {
        "filter": "Application: performance volumegroup"
       },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Read Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:612",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          ":Powerstore MetricVg Read Bandwidth",
          " "
         ],
         "text": "replaceAlias(:Powerstore MetricVg Read Bandwidth,  )"
        },
        {
         "$$hashKey": "object:613",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/Bandwidth Read/" },
       "itemTag": {
        "filter": "Application: performance volumegroup"
       },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Avg Latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:322",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          ":Powerstore MetricVg Avg Latency",
          " "
         ],
         "text": "replaceAlias(:Powerstore MetricVg Avg Latency,  )"
        },
        {
         "$$hashKey": "object:323",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/Latency Total avg/" },
       "itemTag": {
        "filter": "Application: performance volumegroup"
       },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Avg Write Latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:438",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          ":Powerstore MetricVg Avg Write Latency",
          " "
         ],
         "text": "replaceAlias(:Powerstore MetricVg Avg Write Latency,  )"
        },
        {
         "$$hashKey": "object:439",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/Latency Write avg/" },
       "itemTag": {
        "filter": "Application: performance volumegroup"
       },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Avg Read Latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:380",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          ":Powerstore MetricVg Avg Read Latency",
          " "
         ],
         "text": "replaceAlias(:Powerstore MetricVg Avg Read Latency,  )"
        },
        {
         "$$hashKey": "object:381",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/Latency Read avg/" },
       "itemTag": {
        "filter": "Application: performance volumegroup"
       },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    }
   ]
  },
  {
   "title": "Performance EthPort",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Eth Port Bytes Rx Ps",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:841",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          ":Powerstore Metric Eth Port Bytes Rx Ps",
          " "
         ],
         "text": "replaceAlias(:Powerstore Metric Eth Port Bytes Rx Ps,  )"
        },
        {
         "$$hashKey": "object:842",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/Bytes Rx Ps/" },
       "itemTag": { "filter": "Application: metric ethport" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Eth Port Bytes Tx Ps",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:870",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          ":Powerstore Metric Eth Port Bytes Tx Ps",
          " "
         ],
         "text": "replaceAlias(:Powerstore Metric Eth Port Bytes Tx Ps,  )"
        },
        {
         "$$hashKey": "object:871",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/Bytes Tx Ps/" },
       "itemTag": { "filter": "Application: metric ethport" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Eth Port Pkt Rx Ps",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:899",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          ":Powerstore Metric Eth Port Pkt Rx Ps",
          " "
         ],
         "text": "replaceAlias(:Powerstore Metric Eth Port Pkt Rx Ps,  )"
        },
        {
         "$$hashKey": "object:900",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/Pkt Rx Ps/" },
       "itemTag": { "filter": "Application: metric ethport" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Eth Port Pkt Tx Ps",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:928",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          ":Powerstore Metric Eth Port Pkt Tx Ps",
          " "
         ],
         "text": "replaceAlias(:Powerstore Metric Eth Port Pkt Tx Ps,  )"
        },
        {
         "$$hashKey": "object:929",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/Pkt Rx Ps/" },
       "itemTag": { "filter": "Application: metric ethport" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Eth Port Pkt Rx Crc Error Ps",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:957",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          ":Powerstore Metric Eth Port Pkt Rx Crc Error Ps",
          " "
         ],
         "text": "replaceAlias(:Powerstore Metric Eth Port Pkt Rx Crc Error Ps,  )"
        },
        {
         "$$hashKey": "object:958",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/Pkt Rx Crc Error Ps/" },
       "itemTag": { "filter": "Application: metric ethport" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Eth Port Pkt Tx Error Ps",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:986",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          ":Powerstore Metric Eth Port Pkt Tx Error Ps",
          " "
         ],
         "text": "replaceAlias(:Powerstore Metric Eth Port Pkt Tx Error Ps,  )"
        },
        {
         "$$hashKey": "object:987",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/Pkt Tx Error Ps/" },
       "itemTag": { "filter": "Application: metric ethport" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Eth Port Pkt Rx No Buffer Error Ps",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:1015",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          ":Powerstore Metric Eth Port Pkt Rx No Buffer Error Ps",
          " "
         ],
         "text": "replaceAlias(:Powerstore Metric Eth Port Pkt Rx No Buffer Error Ps,  )"
        },
        {
         "$$hashKey": "object:1016",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/Pkt Rx No Buffer Error Ps/" },
       "itemTag": { "filter": "Application: metric ethport" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Performance FcPort",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Avg Latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:1075",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        },
        {
         "$$hashKey": "object:1076",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          ":Powerstore Metric Fc Port Avg Latency",
          " "
         ],
         "text": "replaceAlias(:Powerstore Metric Fc Port Avg Latency,  )"
        },
        {
         "$$hashKey": "object:1077",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "BaseEnclosure-",
          " "
         ],
         "text": "replaceAlias(BaseEnclosure-,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/Avg Latency$/" },
       "itemTag": {
        "filter": "Application: performance fcport"
       },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Avg Read Latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:1106",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        },
        {
         "$$hashKey": "object:1107",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          ":Powerstore Metric Fc Port Avg Read Latency",
          " "
         ],
         "text": "replaceAlias(:Powerstore Metric Fc Port Avg Read Latency,  )"
        },
        {
         "$$hashKey": "object:1108",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "BaseEnclosure-",
          " "
         ],
         "text": "replaceAlias(BaseEnclosure-,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/Avg Latency Read/" },
       "itemTag": {
        "filter": "Application: performance fcport"
       },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Avg Write Latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:1137",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        },
        {
         "$$hashKey": "object:1138",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          ":Powerstore Metric Fc Port Avg Write Latency",
          " "
         ],
         "text": "replaceAlias(:Powerstore Metric Fc Port Avg Write Latency,  )"
        },
        {
         "$$hashKey": "object:1139",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "BaseEnclosure-",
          " "
         ],
         "text": "replaceAlias(BaseEnclosure-,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/Avg Latency Write/" },
       "itemTag": {
        "filter": "Application: performance fcport"
       },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Total Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:1168",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/Bandwidth Total/" },
       "itemTag": {
        "filter": "Application: performance fcport"
       },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Write Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:1195",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        },
        {
         "$$hashKey": "object:1196",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          ":Powerstore Metric Fc Port Write Bandwidth",
          " "
         ],
         "text": "replaceAlias(:Powerstore Metric Fc Port Write Bandwidth,  )"
        },
        {
         "$$hashKey": "object:1197",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "BaseEnclosure-",
          " "
         ],
         "text": "replaceAlias(BaseEnclosure-,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/Bandwidth Write/" },
       "itemTag": {
        "filter": "Application: performance fcport"
       },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Read Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:1226",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        },
        {
         "$$hashKey": "object:1227",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          ":Powerstore Metric Fc Port Read Bandwidth",
          " "
         ],
         "text": "replaceAlias(:Powerstore Metric Fc Port Read Bandwidth,  )"
        },
        {
         "$$hashKey": "object:1228",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "BaseEnclosure-",
          " "
         ],
         "text": "replaceAlias(BaseEnclosure-,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/Bandwidth Read/" },
       "itemTag": {
        "filter": "Application: performance fcport"
       },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "IOPS Total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:1257",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        },
        {
         "$$hashKey": "object:1258",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          ":Powerstore Metric Fc Port Total Iops",
          " "
         ],
         "text": "replaceAlias(:Powerstore Metric Fc Port Total Iops,  )"
        },
        {
         "$$hashKey": "object:1259",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "BaseEnclosure-",
          " "
         ],
         "text": "replaceAlias(BaseEnclosure-,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/IOPS Total/" },
       "itemTag": {
        "filter": "Application: performance fcport"
       },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "IOPS Read",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:1288",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        },
        {
         "$$hashKey": "object:1289",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          ":Powerstore Metric Fc Port Avg Io Size",
          " "
         ],
         "text": "replaceAlias(:Powerstore Metric Fc Port Avg Io Size,  )"
        },
        {
         "$$hashKey": "object:1290",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "BaseEnclosure-",
          " "
         ],
         "text": "replaceAlias(BaseEnclosure-,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/IOPS Read/" },
       "itemTag": {
        "filter": "Application: performance fcport"
       },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "IOPS Write",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:1319",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        },
        {
         "$$hashKey": "object:1320",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          ":Powerstore Metric Fc Port Write Iops",
          " "
         ],
         "text": "replaceAlias(:Powerstore Metric Fc Port Write Iops,  )"
        },
        {
         "$$hashKey": "object:1321",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "BaseEnclosure-",
          " "
         ],
         "text": "replaceAlias(BaseEnclosure-,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/IOPS Write/" },
       "itemTag": {
        "filter": "Application: performance fcport"
       },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Link Failure Count Ps",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:1350",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        },
        {
         "$$hashKey": "object:1351",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "Link Failure Count Ps",
          " "
         ],
         "text": "replaceAlias(Link Failure Count Ps,  )"
        },
        {
         "$$hashKey": "object:1352",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "BaseEnclosure-",
          " "
         ],
         "text": "replaceAlias(BaseEnclosure-,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/Link Failure Count Ps/" },
       "itemTag": {
        "filter": "Application: performance fcport"
       },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Dumped Frames Ps",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:1381",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        },
        {
         "$$hashKey": "object:1382",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "Dumped Frames Ps",
          " "
         ],
         "text": "replaceAlias(Dumped Frames Ps,  )"
        },
        {
         "$$hashKey": "object:1383",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "BaseEnclosure-",
          " "
         ],
         "text": "replaceAlias(BaseEnclosure-,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/Dumped Frames Ps/" },
       "itemTag": {
        "filter": "Application: performance fcport"
       },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Invalid Crc Count Ps",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:1412",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        },
        {
         "$$hashKey": "object:1413",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "Invalid Crc Count Ps",
          " "
         ],
         "text": "replaceAlias(Invalid Crc Count Ps,  )"
        },
        {
         "$$hashKey": "object:1414",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "BaseEnclosure-",
          " "
         ],
         "text": "replaceAlias(BaseEnclosure-,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/Invalid Crc Count Ps/" },
       "itemTag": {
        "filter": "Application: performance fcport"
       },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Loss Of Signal Count Ps",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:1443",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        },
        {
         "$$hashKey": "object:1444",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "Loss Of Signal Count Ps",
          " "
         ],
         "text": "replaceAlias(Loss Of Signal Count Ps,  )"
        },
        {
         "$$hashKey": "object:1445",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "BaseEnclosure-",
          " "
         ],
         "text": "replaceAlias(BaseEnclosure-,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/Loss Of Signal Count Ps/" },
       "itemTag": {
        "filter": "Application: performance fcport"
       },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Loss Of Sync Count Ps",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:1474",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        },
        {
         "$$hashKey": "object:1475",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "Loss Of Sync Count Ps",
          " "
         ],
         "text": "replaceAlias(Loss Of Sync Count Ps,  )"
        },
        {
         "$$hashKey": "object:1476",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "BaseEnclosure-",
          " "
         ],
         "text": "replaceAlias(BaseEnclosure-,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/Loss Of Sync Count Ps/" },
       "itemTag": {
        "filter": "Application: performance fcport"
       },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Invalid Tx Word Count Ps",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:1505",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "$Hosts:",
          " "
         ],
         "text": "replaceAlias($Hosts:,  )"
        },
        {
         "$$hashKey": "object:1506",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "Invalid Tx Word Count Ps",
          " "
         ],
         "text": "replaceAlias(Invalid Tx Word Count Ps,  )"
        },
        {
         "$$hashKey": "object:1507",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "BaseEnclosure-",
          " "
         ],
         "text": "replaceAlias(BaseEnclosure-,  )"
        }
       ],
       "group": { "filter": "$Group" },
       "host": { "filter": "$Hosts" },
       "item": { "filter": "/Invalid Tx Word Count Ps/" },
       "itemTag": {
        "filter": "Application: performance fcport"
       },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  }
 ]
}