{
 "title": "powerstore exporter dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "IP",
    "query": {
     "query": "label_values(powerstore_cluster{},IP)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Information",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "powerstore_cluster{IP=\"$IP\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_appliance{IP=\"$IP\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_perf_io_workload_cpu_utilization{IP=\"$IP\"}*100",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_cap_last_efficiency_ratio{IP=\"$IP\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_cap_last_logical_provisioned{IP=\"$IP\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_cap_last_physical_used{IP=\"$IP\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_cap_last_physical_total{IP=\"$IP\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_cap_last_logical_used{IP=\"$IP\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Powerstore latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "powerstore_perf_avg_latency{IP=\"$IP\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_perf_avg_read_latency{IP=\"$IP\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_perf_avg_write_latency{IP=\"$IP\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Powerstore IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "powerstore_perf_total_iops{IP=\"$IP\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_perf_read_iops{IP=\"$IP\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_perf_write_iops{IP=\"$IP\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Powerstore Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "powerstore_perf_total_bandwidth{IP=\"$IP\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_perf_write_bandwidth{IP=\"$IP\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_perf_read_bandwidth{IP=\"$IP\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Port", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "FcPort latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "powerstore_metricFcPort_avg_latency{IP=\"$IP\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_metricFcPort_avg_read_latency{IP=\"$IP\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_metricFcPort_avg_write_latency{IP=\"$IP\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FcPort IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "powerstore_metricFcPort_read_iops{IP=\"$IP\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_metricFcPort_write_iops{IP=\"$IP\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_metricFcPort_total_iops{IP=\"$IP\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FcPort Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "powerstore_metricFcPort_read_bandwidth{IP=\"$IP\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_metricFcPort_write_bandwidth{IP=\"$IP\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_metricFcPort_total_bandwidth{IP=\"$IP\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FCPort Information",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "powerstore_metricFcPort_prim_seq_prot_err_count_ps{IP=\"$IP\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_metricFcPort_loss_of_sync_count_ps{IP=\"$IP\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_metricFcPort_loss_of_signal_count_ps{IP=\"$IP\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_metricFcPort_link_failure_count_ps{IP=\"$IP\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_metricFcPort_invalid_tx_word_count_ps{IP=\"$IP\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_metricFcPort_invalid_crc_count_ps{IP=\"$IP\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_metricFcPort_dumped_frames_ps{IP=\"$IP\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_port_fc_port_is_link_up{IP=\"$IP\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EthPort Information",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "powerstore_metricEthPort_bytes_rx_ps{IP=\"$IP\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_metricEthPort_bytes_tx_ps{IP=\"$IP\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_metricEthPort_pkt_rx_crc_error_ps{IP=\"$IP\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_metricEthPort_pkt_rx_no_buffer_error_ps{IP=\"$IP\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_metricEthPort_pkt_rx_ps{IP=\"$IP\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_metricEthPort_pkt_tx_error_ps{IP=\"$IP\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_metricEthPort_pkt_tx_ps{IP=\"$IP\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_port_eth_port_is_link_up{IP=\"$IP\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Volume", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Volume Avg Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "powerstore_metricVolume_avg_latency{IP=\"$IP\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Volume Total IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "powerstore_metricVolume_total_iops{IP=\"$IP\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Volume Total Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "powerstore_metricVolume_total_bandwidth{IP=\"$IP\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Volume Information",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "powerstore_volume_size{IP=\"$IP\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_volume_state{IP=\"$IP\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_volume_logical_used{IP=\"$IP\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "hardware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Drive Information",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "powerstore_hardware_drive_drive_type{IP=\"$IP\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_hardware_drive_fips_status{IP=\"$IP\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_hardware_drive_size{IP=\"$IP\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_wear_metrics_by_drive{IP=\"$IP\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}